version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: uztech-php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    restart: always
  db:
    image: mysql:8.0
    container_name: uztech-db
    ports:
      -"3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABSE: uztech
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
